#!/bin/sh

vc_pstd () {
    printf -- "$*"
}

vc_perr () {
    vc_pstd "$@" 1>&2
}

vc_usage () {
    vc_perr "usage: $0 -a action [-c config_file] [-k kickstart_file]\n"
}

vc_get_file_dir () {
    local src

    src="$1"
    while [ -h "${src}" ]; do src="$(readlink "${src}")"; done
    src=$(cd -P $(dirname "${src}") && pwd)

    vc_pstd "${src}"
}

vc_check_file_readable () {
    if [ ! -r "$1" ]; then
        vc_perr "$0: cannot read file -- $1\n"
        vc_usage
        return 1
    fi
    vc_pstd "$1"
}

vc_parse_options () {
    . "${ROOT_DIR}/etc/box.conf"
}

vc_parse_local_options () {
    local conflocal

    conflocal="${ROOT_DIR}/etc/box.conf.local"

    if [ ! -z "$1" ]; then
        conflocal="$1"
    fi

    if [ -r "${conflocal}" ]; then
        . "${conflocal}"
    fi
}

vc_parse_args () {
    local arg
    local args

    OPTIND=1

    while getopts ":a:c:k:" opt; do
        case ${opt} in
            a)
                case "${OPTARG}" in
                    initialize|cleanup)
                        ACTION="${OPTARG}"
                        ;;
                    *)
                        vc_perr "$0: unrecognised action -- ${OPTARG}\n"
                        vc_usage
                        exit 3
                        ;;
                esac
                ;;
            c)
                C_CONFIG_LOCAL="$(vc_check_file_readable "${OPTARG}")" \
                    || exit 8
                ;;
            k)
                C_KICKSTART="$(vc_check_file_readable "${OPTARG}")" \
                    || exit 9
                ;;
            \?)
                vc_perr "$0: illegal opt -- ${OPTARG}\n"
                vc_usage
                exit 1
                ;;
            :)
                case ${OPTARG} in
                    a)
                        vc_perr "$0: no action was specified\n"
                        vc_usage
                        exit 5
                        ;;
                    c)
                        vc_perr "$0: no config file was specified\n"
                        vc_usage
                        exit 6
                        ;;
                    k)
                        vc_perr "$0: no kickstart file was specified\n"
                        vc_usage
                        exit 7
                        ;;
                esac
                ;;
        esac
    done

    shift $(( OPTIND - 1 ))
    if [ ! $# -eq 0 ]; then
        vc_perr "$0: options not understood -- $@\n"
        vc_usage
        exit 10
    fi
}


ROOT_DIR=$(vc_get_file_dir $0)

. "${ROOT_DIR}/src/initialize.sh"
. "${ROOT_DIR}/src/cleanup.sh"

vc_parse_options
vc_parse_args "$@"
vc_parse_local_options "${C_CONFIG_LOCAL}"

case "${ACTION}" in
    initialize)
        vc_action_initialize
        ;;
    cleanup)
        vc_action_cleanup
        ;;
    *)
        vc_perr "$0: no action was specified\n"
        vc_usage
        exit 5
esac
