#!/bin/sh

vc_printerr () {
    printf "$@" 1>&2
}

vc_usage () {
    vc_printerr "usage: $0"
    vc_printerr " action\n"
}

vc_get_file_dir () {
    local src

    src="$1"
    while [ -h "${src}" ]; do src="$(readlink "${src}")"; done
    src=$(cd -P $(dirname "${src}") && pwd)

    printf "${src}"
}

vc_check_file_readable () {
    if [ ! -r "$1" ]; then
        vc_printerr "$0: Cannot read file: \"$1\".\n\n"
        vc_usage
        exit 2
    fi
    printf "$1"
}

vc_parse_options () {
    . "${ROOT_DIR}/etc/box.conf"
}

vc_parse_args () {
    local arg
    local args

    args=$(getopt -n "$0" "$@")
    if [ $? -ne 0 ]; then
        vc_usage
        exit 1
    fi

    set -- ${args}
    for arg in "$@"; do
        case "${arg}" in
            --)
                shift
                break
                ;;
        esac
    done

    case "$1" in
        initialize|cleanup)
            ACTION="$1"; shift
            ;;
        *)
            vc_printerr "$0: Unrecognised action: \"$1\".\n\n"
            vc_usage
            exit 3
            ;;
    esac
}


ROOT_DIR=$(vc_get_file_dir $0)

. "${ROOT_DIR}/src/initialize.sh"
. "${ROOT_DIR}/src/cleanup.sh"

vc_parse_options
vc_parse_args "$@"

case "${ACTION}" in
    initialize)
        vc_action_initialize
        ;;
    cleanup)
        vc_action_cleanup
        ;;
esac
