#!/bin/sh -e

. ./vars.sh

VBoxManage createvm --name ${NAME} --ostype ${TYPE} --register

VBoxManage modifyvm ${NAME} \
    --vram 12 \
    --accelerate3d off \
    --memory 613 \
    --usb off \
    --audio none \
    --boot1 disk --boot2 dvd --boot3 none --boot4 none \
    --nictype1 virtio --nic1 nat --natnet1 "${NATNET}" \
    --nictype2 virtio \
    --nictype3 virtio \
    --nictype4 virtio \
    --acpi on --ioapic off \
    --chipset piix3 \
    --rtcuseutc on \
    --hpet on \
    --bioslogofadein off \
    --bioslogofadeout off \
    --bioslogodisplaytime 0 \
    --biosbootmenu disabled

VBoxManage createhd --filename "${HDD}" --size 8192
# Swap is recommended to be double the size of RAM.
VBoxManage createhd --filename "${HDD_SWAP}" --size 1226

VBoxManage storagectl ${NAME} \
    --name SATA --add sata --portcount 2 --bootable on

VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 0 --type hdd --medium "${HDD}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 1 --type hdd --medium "${HDD_SWAP}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 2 --type dvddrive --medium "${INSTALLER}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 3 --type dvddrive --medium "${GUESTADDITIONS}"

VBoxManage startvm ${NAME} --type gui

setup_ruby() {
    # handle errors in here
    set +e

    SOURCE=$(which vagrant)
    if [ $? -eq 0 ]; then
        while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
        EMBEDDED_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )/../embedded"

        unset RUBYOPT
        RUBY_EXECUTABLE="${EMBEDDED_DIR}/bin/ruby"
    else
        RUBY_EXECUTABLE=$(which ruby)
        if [ ! $? -eq 0 ]; then
            echo "Cannot find Ruby (needed for kickstart file)"
            exit 1
        fi
    fi

    set -e
}

# This only really caters for the common case. If you have problems, please
# discover your host's IP address and adjust accordingly.
IP=`echo ${NATNET} | sed -nE 's/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}).*/\1/p'`

setup_ruby

echo 'At the boot prompt, hit <TAB> and then type:'
/bin/echo -n " ks=http://${IP}.3:"
${RUBY_EXECUTABLE} httpd.rb ks.cfg

echo When finished:
echo "./cleanup && vagrant package --base ${NAME} --output boxes/${NAME}-`date +%Y%m%d`.box"
